/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "moda.h"
#include "aes.h"
#include "aes_gcm.h"

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_MODA_AES_GCM_Encrypt_notext_noaad(void);
extern void test_MODA_AES_GCM_Encrypt_notext(void);
extern void test_MODA_AES_GCM_Encrypt_notext_partaad(void);
extern void test_MODA_AES_GCM_Encrypt_noaad(void);
extern void test_MODA_AES_GCM_Encrypt_parttext_noaad(void);
extern void test_MODA_AES_GCM_Encrypt(void);
extern void test_MODA_AES_GCM_Encrypt_oddiv(void);
extern void test_MODA_AES_GCM_Decrypt_notext_noaad(void);
extern void test_MODA_AES_GCM_Decrypt_notext(void);
extern void test_MODA_AES_GCM_Decrypt_notext_partaad(void);
extern void test_MODA_AES_GCM_Decrypt_noaad(void);
extern void test_MODA_AES_GCM_Decrypt_parttext_noaad(void);
extern void test_MODA_AES_GCM_Decrypt(void);
extern void test_MODA_AES_GCM_Decrypt_oddiv(void);


//=======Test Reset Option=====
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  UnityBegin("tests/moda/aes_gcm/test_aes_gcm.c");
  RUN_TEST(test_MODA_AES_GCM_Encrypt_notext_noaad, 7);
  RUN_TEST(test_MODA_AES_GCM_Encrypt_notext, 7);
  RUN_TEST(test_MODA_AES_GCM_Encrypt_notext_partaad, 43);
  RUN_TEST(test_MODA_AES_GCM_Encrypt_noaad, 61);
  RUN_TEST(test_MODA_AES_GCM_Encrypt_parttext_noaad, 81);
  RUN_TEST(test_MODA_AES_GCM_Encrypt, 81);
  RUN_TEST(test_MODA_AES_GCM_Encrypt_oddiv, 121);
  RUN_TEST(test_MODA_AES_GCM_Decrypt_notext_noaad, 141);
  RUN_TEST(test_MODA_AES_GCM_Decrypt_notext, 141);
  RUN_TEST(test_MODA_AES_GCM_Decrypt_notext_partaad, 184);
  RUN_TEST(test_MODA_AES_GCM_Decrypt_noaad, 205);
  RUN_TEST(test_MODA_AES_GCM_Decrypt_parttext_noaad, 228);
  RUN_TEST(test_MODA_AES_GCM_Decrypt, 228);
  RUN_TEST(test_MODA_AES_GCM_Decrypt_oddiv, 274);

  return (UnityEnd());
}
