/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "moda.h"
#include "aes.h"
#include <string.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_MODA_AES_Init(void);
extern void test_MODA_AES_Encrypt_128(void);
extern void test_MODA_AES_Encrypt_192(void);
extern void test_MODA_AES_Encrypt_256(void);
extern void test_MODA_AES_Decrypt_128(void);
extern void test_MODA_AES_Decrypt_192(void);
extern void test_MODA_AES_Decrypt_256(void);


//=======Test Reset Option=====
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  UnityBegin("tests/moda/aes/test_aes.c");
  RUN_TEST(test_MODA_AES_Init, 8);
  RUN_TEST(test_MODA_AES_Encrypt_128, 18);
  RUN_TEST(test_MODA_AES_Encrypt_192, 34);
  RUN_TEST(test_MODA_AES_Encrypt_256, 50);
  RUN_TEST(test_MODA_AES_Decrypt_128, 66);
  RUN_TEST(test_MODA_AES_Decrypt_192, 82);
  RUN_TEST(test_MODA_AES_Decrypt_256, 98);

  return (UnityEnd());
}
